// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk3hGW2wbeEeP-8rqleHMYWV2V7FDws4U',
    appId: '1:717246952953:web:30018d201b81631953b928',
    messagingSenderId: '717246952953',
    projectId: 'sat-sen-app',
    authDomain: 'sat-sen-app.firebaseapp.com',
    storageBucket: 'sat-sen-app.firebasestorage.app',
    measurementId: 'G-XP3HZDGERG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2j5dv8CadUQYeL0NWmJ2fr1TuJYquOE',
    appId: '1:717246952953:android:6179ecf16ddd05bb53b928',
    messagingSenderId: '717246952953',
    projectId: 'sat-sen-app',
    storageBucket: 'sat-sen-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_nB33lJ_82AI1MCz8A9Ks3vy5Y9AMbM',
    appId: '1:717246952953:ios:717c2e904ecf770b53b928',
    messagingSenderId: '717246952953',
    projectId: 'sat-sen-app',
    storageBucket: 'sat-sen-app.firebasestorage.app',
    iosBundleId: 'com.satsen.satSenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_nB33lJ_82AI1MCz8A9Ks3vy5Y9AMbM',
    appId: '1:717246952953:ios:717c2e904ecf770b53b928',
    messagingSenderId: '717246952953',
    projectId: 'sat-sen-app',
    storageBucket: 'sat-sen-app.firebasestorage.app',
    iosBundleId: 'com.satsen.satSenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk3hGW2wbeEeP-8rqleHMYWV2V7FDws4U',
    appId: '1:717246952953:web:ef29b427d587847953b928',
    messagingSenderId: '717246952953',
    projectId: 'sat-sen-app',
    authDomain: 'sat-sen-app.firebaseapp.com',
    storageBucket: 'sat-sen-app.firebasestorage.app',
    measurementId: 'G-0X31YQ8EWM',
  );
}
